language: php
php:
  - 5.5
  - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.6.1 WP_MULTISITE=0
    - WP_VERSION=3.6.1 WP_MULTISITE=1
    - WP_VSERION=4.0.1 WP_MULISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit

